# Form implementation generated from reading ui file 'UI/AddNoteWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddNoteWindow(object):
    def setupUi(self, AddNoteWindow):
        AddNoteWindow.setObjectName("AddNoteWindow")
        AddNoteWindow.resize(421, 552)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(AddNoteWindow)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=AddNoteWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.noteTabTittle = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.noteTabTittle.setFont(font)
        self.noteTabTittle.setObjectName("noteTabTittle")
        self.verticalLayout.addWidget(self.noteTabTittle, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=AddNoteWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.noteSelectedDate = QtWidgets.QCalendarWidget(parent=self.frame_2)
        self.noteSelectedDate.setObjectName("noteSelectedDate")
        self.verticalLayout_2.addWidget(self.noteSelectedDate)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=AddNoteWindow)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.noteTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_3)
        self.noteTextEdit.setObjectName("noteTextEdit")
        self.verticalLayout_3.addWidget(self.noteTextEdit)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=AddNoteWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_button = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 255, 255);\n"
"margin-right: 2 px;\n"
"margin-left: 2px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(224, 224, 224);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(224, 224, 224, 40);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/add_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_button.setIcon(icon)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.verticalLayout_4.addWidget(self.frame_4)

        self.retranslateUi(AddNoteWindow)
        QtCore.QMetaObject.connectSlotsByName(AddNoteWindow)

    def retranslateUi(self, AddNoteWindow):
        _translate = QtCore.QCoreApplication.translate
        AddNoteWindow.setWindowTitle(_translate("AddNoteWindow", "Dialog"))
        self.noteTabTittle.setText(_translate("AddNoteWindow", "Add note"))
        self.noteTextEdit.setPlaceholderText(_translate("AddNoteWindow", "Note"))
        self.add_button.setText(_translate("AddNoteWindow", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNoteWindow = QtWidgets.QDialog()
    ui = Ui_AddNoteWindow()
    ui.setupUi(AddNoteWindow)
    AddNoteWindow.show()
    sys.exit(app.exec())
