# Form implementation generated from reading ui file 'UI/LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 548)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(parent=LoginWindow)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainTabLabel = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.mainTabLabel.setFont(font)
        self.mainTabLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mainTabLabel.setObjectName("mainTabLabel")
        self.horizontalLayout.addWidget(self.mainTabLabel)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginWarningLabel = QtWidgets.QLabel(parent=self.frame_2)
        self.loginWarningLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.loginWarningLabel.setObjectName("loginWarningLabel")
        self.verticalLayout.addWidget(self.loginWarningLabel)
        self.loginLabelEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.loginLabelEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.loginLabelEdit.setObjectName("loginLabelEdit")
        self.verticalLayout.addWidget(self.loginLabelEdit)
        self.passwordWarningLabel = QtWidgets.QLabel(parent=self.frame_2)
        self.passwordWarningLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.passwordWarningLabel.setObjectName("passwordWarningLabel")
        self.verticalLayout.addWidget(self.passwordWarningLabel)
        self.passwordLabelEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.passwordLabelEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.passwordLabelEdit.setObjectName("passwordLabelEdit")
        self.verticalLayout.addWidget(self.passwordLabelEdit)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=LoginWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sign_in_button = QtWidgets.QPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sign_in_button.sizePolicy().hasHeightForWidth())
        self.sign_in_button.setSizePolicy(sizePolicy)
        self.sign_in_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sign_in_button.setFont(font)
        self.sign_in_button.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 255, 255);\n"
"margin-right: 2 px;\n"
"margin-left: 2px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(224, 224, 224);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(224, 224, 224, 40);\n"
"}\n"
"")
        self.sign_in_button.setObjectName("sign_in_button")
        self.verticalLayout_2.addWidget(self.sign_in_button)
        self.sign_up_button = QtWidgets.QPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sign_up_button.sizePolicy().hasHeightForWidth())
        self.sign_up_button.setSizePolicy(sizePolicy)
        self.sign_up_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 255, 255);\n"
"margin-right: 2 px;\n"
"margin-left: 2px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(224, 224, 224);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(224, 224, 224, 40);\n"
"}\n"
"")
        self.sign_up_button.setObjectName("sign_up_button")
        self.verticalLayout_2.addWidget(self.sign_up_button)
        self.verticalLayout_3.addWidget(self.frame_3)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Dialog"))
        self.mainTabLabel.setText(_translate("LoginWindow", "All notes app"))
        self.loginWarningLabel.setText(_translate("LoginWindow", "loginWarning"))
        self.loginLabelEdit.setPlaceholderText(_translate("LoginWindow", "Login"))
        self.passwordWarningLabel.setText(_translate("LoginWindow", "passwordWarning"))
        self.passwordLabelEdit.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.sign_in_button.setText(_translate("LoginWindow", "Sign In"))
        self.sign_up_button.setText(_translate("LoginWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QDialog()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec())
